### ISSUE TITLE
error plugin activate all

### ISSUE THREAD

**Issue by camphi** [DigitalPygmalion/badge-factor-boilerplate#2]
./wp-cli.phar plugin activate --all
Plugin 'advanced-custom-fields' activated.
PHP Fatal error:  Uncaught Error: Call to undefined function badgeos_flush_rewrite_rules() in /home/camphi/badge-factor/web/app/plugins/badge-factor/badgefactor.php:138
Stack trace:
#0 /home/camphi/badge-factor/web/wp/wp-includes/class-wp-hook.php(298): BadgeFactor->activate(NULL)
#1 /home/camphi/badge-factor/web/wp/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#2 /home/camphi/badge-factor/web/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/camphi/badge-factor/web/wp/wp-admin/includes/plugin.php(591): do_action('activate_badge-...', NULL)
#4 phar:///home/camphi/badge-factor/wp-cli.phar/php/commands/plugin.php(284): activate_plugin('badge-factor/ba...', '', NULL)
#5 [internal function]: Plugin_Command->activate(Array, Array)
#6 phar:///home/camphi/badge-factor/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///home/camphi/badge-factor in /home/camphi/badge-factor/web/app/plugins/badge-factor/badgefactor.php on line 138
Fatal error: Uncaught Error: Call to undefined function badgeos_flush_rewrite_rules() in /home/camphi/badge-factor/web/app/plugins/badge-factor/badgefactor.php:138
Stack trace:
#0 /home/camphi/badge-factor/web/wp/wp-includes/class-wp-hook.php(298): BadgeFactor->activate(NULL)
#1 /home/camphi/badge-factor/web/wp/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#2 /home/camphi/badge-factor/web/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home/camphi/badge-factor/web/wp/wp-admin/includes/plugin.php(591): do_action('activate_badge-...', NULL)
#4 phar:///home/camphi/badge-factor/wp-cli.phar/php/commands/plugin.php(284): activate_plugin('badge-factor/ba...', '', NULL)
#5 [internal function]: Plugin_Command->activate(Array, Array)
#6 phar:///home/camphi/badge-factor/wp-cli.phar/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///home/camphi/badge-factor in /home/camphi/badge-factor/web/app/plugins/badge-factor/badgefactor.php on line 138

**Comment by camphi** [comment]
Corrected with : https://github.com/DigitalPygmalion/badge-factor/commit/0ac72d9e6aab0c00104d22f180e6e691363e0439
